(cl:in-package skiros2_msgs-msg)
(cl:export '(ROBOT-VAL
          ROBOT
          TASK_ID-VAL
          TASK_ID
          ID-VAL
          ID
          PARENT_LABEL-VAL
          PARENT_LABEL
          PARENT_ID-VAL
          PARENT_ID
          TYPE-VAL
          TYPE
          LABEL-VAL
          LABEL
          PARAMS-VAL
          PARAMS
          PROCESSOR-VAL
          PROCESSOR
          STATE-VAL
          STATE
          PROGRESS_CODE-VAL
          PROGRESS_CODE
          PROGRESS_PERIOD-VAL
          PROGRESS_PERIOD
          PROGRESS_TIME-VAL
          PROGRESS_TIME
          PROGRESS_MESSAGE-VAL
          PROGRESS_MESSAGE
))