; Auto-generated. Do not edit!


(cl:in-package skiros2_msgs-msg)


;//! \htmlinclude AssignTaskGoal.msg.html

(cl:defclass <AssignTaskGoal> (roslisp-msg-protocol:ros-message)
  ((author
    :reader author
    :initarg :author
    :type cl:string
    :initform "")
   (goals
    :reader goals
    :initarg :goals
    :type cl:string
    :initform ""))
)

(cl:defclass AssignTaskGoal (<AssignTaskGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AssignTaskGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AssignTaskGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name skiros2_msgs-msg:<AssignTaskGoal> is deprecated: use skiros2_msgs-msg:AssignTaskGoal instead.")))

(cl:ensure-generic-function 'author-val :lambda-list '(m))
(cl:defmethod author-val ((m <AssignTaskGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader skiros2_msgs-msg:author-val is deprecated.  Use skiros2_msgs-msg:author instead.")
  (author m))

(cl:ensure-generic-function 'goals-val :lambda-list '(m))
(cl:defmethod goals-val ((m <AssignTaskGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader skiros2_msgs-msg:goals-val is deprecated.  Use skiros2_msgs-msg:goals instead.")
  (goals m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AssignTaskGoal>) ostream)
  "Serializes a message object of type '<AssignTaskGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'author))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'author))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goals))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goals))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AssignTaskGoal>) istream)
  "Deserializes a message object of type '<AssignTaskGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'author) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'author) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goals) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goals) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AssignTaskGoal>)))
  "Returns string type for a message object of type '<AssignTaskGoal>"
  "skiros2_msgs/AssignTaskGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AssignTaskGoal)))
  "Returns string type for a message object of type 'AssignTaskGoal"
  "skiros2_msgs/AssignTaskGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AssignTaskGoal>)))
  "Returns md5sum for a message object of type '<AssignTaskGoal>"
  "2e85394eee2ae974ce4d404b5bf05f46")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AssignTaskGoal)))
  "Returns md5sum for a message object of type 'AssignTaskGoal"
  "2e85394eee2ae974ce4d404b5bf05f46")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AssignTaskGoal>)))
  "Returns full string definition for message of type '<AssignTaskGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string author~%string goals #PDDL format~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AssignTaskGoal)))
  "Returns full string definition for message of type 'AssignTaskGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string author~%string goals #PDDL format~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AssignTaskGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'author))
     4 (cl:length (cl:slot-value msg 'goals))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AssignTaskGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AssignTaskGoal
    (cl:cons ':author (author msg))
    (cl:cons ':goals (goals msg))
))
