// Generated by gencpp from file skiros2_msgs/AssignTaskGoal.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_ASSIGNTASKGOAL_H
#define SKIROS2_MSGS_MESSAGE_ASSIGNTASKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace skiros2_msgs
{
template <class ContainerAllocator>
struct AssignTaskGoal_
{
  typedef AssignTaskGoal_<ContainerAllocator> Type;

  AssignTaskGoal_()
    : author()
    , goals()  {
    }
  AssignTaskGoal_(const ContainerAllocator& _alloc)
    : author(_alloc)
    , goals(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _author_type;
  _author_type author;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AssignTaskGoal_

typedef ::skiros2_msgs::AssignTaskGoal_<std::allocator<void> > AssignTaskGoal;

typedef boost::shared_ptr< ::skiros2_msgs::AssignTaskGoal > AssignTaskGoalPtr;
typedef boost::shared_ptr< ::skiros2_msgs::AssignTaskGoal const> AssignTaskGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator1> & lhs, const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator2> & rhs)
{
  return lhs.author == rhs.author &&
    lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator1> & lhs, const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e85394eee2ae974ce4d404b5bf05f46";
  }

  static const char* value(const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e85394eee2ae974ULL;
  static const uint64_t static_value2 = 0xce4d404b5bf05f46ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/AssignTaskGoal";
  }

  static const char* value(const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string author\n"
"string goals #PDDL format\n"
;
  }

  static const char* value(const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.author);
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignTaskGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::AssignTaskGoal_<ContainerAllocator>& v)
  {
    s << indent << "author: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.author);
    s << indent << "goals: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goals);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_ASSIGNTASKGOAL_H
