// Generated by gencpp from file skiros2_msgs/ResourceGetDescriptions.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_RESOURCEGETDESCRIPTIONS_H
#define SKIROS2_MSGS_MESSAGE_RESOURCEGETDESCRIPTIONS_H

#include <ros/service_traits.h>


#include <skiros2_msgs/ResourceGetDescriptionsRequest.h>
#include <skiros2_msgs/ResourceGetDescriptionsResponse.h>


namespace skiros2_msgs
{

struct ResourceGetDescriptions
{

typedef ResourceGetDescriptionsRequest Request;
typedef ResourceGetDescriptionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResourceGetDescriptions
} // namespace skiros2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skiros2_msgs::ResourceGetDescriptions > {
  static const char* value()
  {
    return "689dba5a19baf7321e2b246602dfca10";
  }

  static const char* value(const ::skiros2_msgs::ResourceGetDescriptions&) { return value(); }
};

template<>
struct DataType< ::skiros2_msgs::ResourceGetDescriptions > {
  static const char* value()
  {
    return "skiros2_msgs/ResourceGetDescriptions";
  }

  static const char* value(const ::skiros2_msgs::ResourceGetDescriptions&) { return value(); }
};


// service_traits::MD5Sum< ::skiros2_msgs::ResourceGetDescriptionsRequest> should match
// service_traits::MD5Sum< ::skiros2_msgs::ResourceGetDescriptions >
template<>
struct MD5Sum< ::skiros2_msgs::ResourceGetDescriptionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::ResourceGetDescriptions >::value();
  }
  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::ResourceGetDescriptionsRequest> should match
// service_traits::DataType< ::skiros2_msgs::ResourceGetDescriptions >
template<>
struct DataType< ::skiros2_msgs::ResourceGetDescriptionsRequest>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::ResourceGetDescriptions >::value();
  }
  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skiros2_msgs::ResourceGetDescriptionsResponse> should match
// service_traits::MD5Sum< ::skiros2_msgs::ResourceGetDescriptions >
template<>
struct MD5Sum< ::skiros2_msgs::ResourceGetDescriptionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::ResourceGetDescriptions >::value();
  }
  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::ResourceGetDescriptionsResponse> should match
// service_traits::DataType< ::skiros2_msgs::ResourceGetDescriptions >
template<>
struct DataType< ::skiros2_msgs::ResourceGetDescriptionsResponse>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::ResourceGetDescriptions >::value();
  }
  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_RESOURCEGETDESCRIPTIONS_H
