// Generated by gencpp from file skiros2_msgs/ResourceGetDescriptionsResponse.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_RESOURCEGETDESCRIPTIONSRESPONSE_H
#define SKIROS2_MSGS_MESSAGE_RESOURCEGETDESCRIPTIONSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skiros2_msgs/ResourceDescription.h>

namespace skiros2_msgs
{
template <class ContainerAllocator>
struct ResourceGetDescriptionsResponse_
{
  typedef ResourceGetDescriptionsResponse_<ContainerAllocator> Type;

  ResourceGetDescriptionsResponse_()
    : list()  {
    }
  ResourceGetDescriptionsResponse_(const ContainerAllocator& _alloc)
    : list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >> _list_type;
  _list_type list;





  typedef boost::shared_ptr< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResourceGetDescriptionsResponse_

typedef ::skiros2_msgs::ResourceGetDescriptionsResponse_<std::allocator<void> > ResourceGetDescriptionsResponse;

typedef boost::shared_ptr< ::skiros2_msgs::ResourceGetDescriptionsResponse > ResourceGetDescriptionsResponsePtr;
typedef boost::shared_ptr< ::skiros2_msgs::ResourceGetDescriptionsResponse const> ResourceGetDescriptionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.list == rhs.list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "689dba5a19baf7321e2b246602dfca10";
  }

  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x689dba5a19baf732ULL;
  static const uint64_t static_value2 = 0x1e2b246602dfca10ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/ResourceGetDescriptionsResponse";
  }

  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ResourceDescription[] list\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/ResourceDescription\n"
"string type\n"
"string name\n"
"Param[] params\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Param\n"
"string param\n"
;
  }

  static const char* value(const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResourceGetDescriptionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::ResourceGetDescriptionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >::stream(s, indent + "    ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_RESOURCEGETDESCRIPTIONSRESPONSE_H
