// Generated by gencpp from file skiros2_msgs/ResourceDescription.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_RESOURCEDESCRIPTION_H
#define SKIROS2_MSGS_MESSAGE_RESOURCEDESCRIPTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skiros2_msgs/Param.h>

namespace skiros2_msgs
{
template <class ContainerAllocator>
struct ResourceDescription_
{
  typedef ResourceDescription_<ContainerAllocator> Type;

  ResourceDescription_()
    : type()
    , name()
    , params()  {
    }
  ResourceDescription_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , name(_alloc)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::vector< ::skiros2_msgs::Param_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::skiros2_msgs::Param_<ContainerAllocator> >> _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> const> ConstPtr;

}; // struct ResourceDescription_

typedef ::skiros2_msgs::ResourceDescription_<std::allocator<void> > ResourceDescription;

typedef boost::shared_ptr< ::skiros2_msgs::ResourceDescription > ResourceDescriptionPtr;
typedef boost::shared_ptr< ::skiros2_msgs::ResourceDescription const> ResourceDescriptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::ResourceDescription_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::ResourceDescription_<ContainerAllocator1> & lhs, const ::skiros2_msgs::ResourceDescription_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.name == rhs.name &&
    lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::ResourceDescription_<ContainerAllocator1> & lhs, const ::skiros2_msgs::ResourceDescription_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f305b743733527b01e745de4106cca51";
  }

  static const char* value(const ::skiros2_msgs::ResourceDescription_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf305b743733527b0ULL;
  static const uint64_t static_value2 = 0x1e745de4106cca51ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/ResourceDescription";
  }

  static const char* value(const ::skiros2_msgs::ResourceDescription_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"string name\n"
"Param[] params\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Param\n"
"string param\n"
;
  }

  static const char* value(const ::skiros2_msgs::ResourceDescription_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.name);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResourceDescription_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::ResourceDescription_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::ResourceDescription_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skiros2_msgs::Param_<ContainerAllocator> >::stream(s, indent + "    ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_RESOURCEDESCRIPTION_H
