// Generated by gencpp from file skiros2_msgs/SkillCommandResponse.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_SKILLCOMMANDRESPONSE_H
#define SKIROS2_MSGS_MESSAGE_SKILLCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace skiros2_msgs
{
template <class ContainerAllocator>
struct SkillCommandResponse_
{
  typedef SkillCommandResponse_<ContainerAllocator> Type;

  SkillCommandResponse_()
    : ok(false)
    , execution_id(0)  {
    }
  SkillCommandResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , execution_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef int16_t _execution_id_type;
  _execution_id_type execution_id;





  typedef boost::shared_ptr< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SkillCommandResponse_

typedef ::skiros2_msgs::SkillCommandResponse_<std::allocator<void> > SkillCommandResponse;

typedef boost::shared_ptr< ::skiros2_msgs::SkillCommandResponse > SkillCommandResponsePtr;
typedef boost::shared_ptr< ::skiros2_msgs::SkillCommandResponse const> SkillCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok &&
    lhs.execution_id == rhs.execution_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39fa93da1f696211b1743331912b2e48";
  }

  static const char* value(const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39fa93da1f696211ULL;
  static const uint64_t static_value2 = 0xb1743331912b2e48ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/SkillCommandResponse";
  }

  static const char* value(const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"int16 execution_id\n"
"\n"
;
  }

  static const char* value(const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.execution_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SkillCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::SkillCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "execution_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.execution_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_SKILLCOMMANDRESPONSE_H
