// Generated by gencpp from file skiros2_msgs/SkillCommand.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_SKILLCOMMAND_H
#define SKIROS2_MSGS_MESSAGE_SKILLCOMMAND_H

#include <ros/service_traits.h>


#include <skiros2_msgs/SkillCommandRequest.h>
#include <skiros2_msgs/SkillCommandResponse.h>


namespace skiros2_msgs
{

struct SkillCommand
{

typedef SkillCommandRequest Request;
typedef SkillCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SkillCommand
} // namespace skiros2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skiros2_msgs::SkillCommand > {
  static const char* value()
  {
    return "1150e5b3a081e2e52deee5d82d9efb98";
  }

  static const char* value(const ::skiros2_msgs::SkillCommand&) { return value(); }
};

template<>
struct DataType< ::skiros2_msgs::SkillCommand > {
  static const char* value()
  {
    return "skiros2_msgs/SkillCommand";
  }

  static const char* value(const ::skiros2_msgs::SkillCommand&) { return value(); }
};


// service_traits::MD5Sum< ::skiros2_msgs::SkillCommandRequest> should match
// service_traits::MD5Sum< ::skiros2_msgs::SkillCommand >
template<>
struct MD5Sum< ::skiros2_msgs::SkillCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::SkillCommand >::value();
  }
  static const char* value(const ::skiros2_msgs::SkillCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::SkillCommandRequest> should match
// service_traits::DataType< ::skiros2_msgs::SkillCommand >
template<>
struct DataType< ::skiros2_msgs::SkillCommandRequest>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::SkillCommand >::value();
  }
  static const char* value(const ::skiros2_msgs::SkillCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skiros2_msgs::SkillCommandResponse> should match
// service_traits::MD5Sum< ::skiros2_msgs::SkillCommand >
template<>
struct MD5Sum< ::skiros2_msgs::SkillCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::SkillCommand >::value();
  }
  static const char* value(const ::skiros2_msgs::SkillCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::SkillCommandResponse> should match
// service_traits::DataType< ::skiros2_msgs::SkillCommand >
template<>
struct DataType< ::skiros2_msgs::SkillCommandResponse>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::SkillCommand >::value();
  }
  static const char* value(const ::skiros2_msgs::SkillCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_SKILLCOMMAND_H
