// Generated by gencpp from file skiros2_msgs/WmGet.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WMGET_H
#define SKIROS2_MSGS_MESSAGE_WMGET_H

#include <ros/service_traits.h>


#include <skiros2_msgs/WmGetRequest.h>
#include <skiros2_msgs/WmGetResponse.h>


namespace skiros2_msgs
{

struct WmGet
{

typedef WmGetRequest Request;
typedef WmGetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WmGet
} // namespace skiros2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skiros2_msgs::WmGet > {
  static const char* value()
  {
    return "a03c7fe28a0cdf8073d54434e678721d";
  }

  static const char* value(const ::skiros2_msgs::WmGet&) { return value(); }
};

template<>
struct DataType< ::skiros2_msgs::WmGet > {
  static const char* value()
  {
    return "skiros2_msgs/WmGet";
  }

  static const char* value(const ::skiros2_msgs::WmGet&) { return value(); }
};


// service_traits::MD5Sum< ::skiros2_msgs::WmGetRequest> should match
// service_traits::MD5Sum< ::skiros2_msgs::WmGet >
template<>
struct MD5Sum< ::skiros2_msgs::WmGetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WmGet >::value();
  }
  static const char* value(const ::skiros2_msgs::WmGetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WmGetRequest> should match
// service_traits::DataType< ::skiros2_msgs::WmGet >
template<>
struct DataType< ::skiros2_msgs::WmGetRequest>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WmGet >::value();
  }
  static const char* value(const ::skiros2_msgs::WmGetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skiros2_msgs::WmGetResponse> should match
// service_traits::MD5Sum< ::skiros2_msgs::WmGet >
template<>
struct MD5Sum< ::skiros2_msgs::WmGetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WmGet >::value();
  }
  static const char* value(const ::skiros2_msgs::WmGetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WmGetResponse> should match
// service_traits::DataType< ::skiros2_msgs::WmGet >
template<>
struct DataType< ::skiros2_msgs::WmGetResponse>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WmGet >::value();
  }
  static const char* value(const ::skiros2_msgs::WmGetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WMGET_H
