// Generated by gencpp from file skiros2_msgs/WmGetRequest.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WMGETREQUEST_H
#define SKIROS2_MSGS_MESSAGE_WMGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skiros2_msgs/WmElement.h>

namespace skiros2_msgs
{
template <class ContainerAllocator>
struct WmGetRequest_
{
  typedef WmGetRequest_<ContainerAllocator> Type;

  WmGetRequest_()
    : action()
    , context()
    , element()
    , relation_filter()
    , type_filter()  {
    }
  WmGetRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , context(_alloc)
    , element(_alloc)
    , relation_filter(_alloc)
    , type_filter(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _context_type;
  _context_type context;

   typedef  ::skiros2_msgs::WmElement_<ContainerAllocator>  _element_type;
  _element_type element;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _relation_filter_type;
  _relation_filter_type relation_filter;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_filter_type;
  _type_filter_type type_filter;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GET)
  #undef GET
#endif
#if defined(_WIN32) && defined(GET_TEMPLATE)
  #undef GET_TEMPLATE
#endif
#if defined(_WIN32) && defined(RESOLVE)
  #undef RESOLVE
#endif
#if defined(_WIN32) && defined(GET_RECURSIVE)
  #undef GET_RECURSIVE
#endif


  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> GET;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> GET_TEMPLATE;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> RESOLVE;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> GET_RECURSIVE;

  typedef boost::shared_ptr< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WmGetRequest_

typedef ::skiros2_msgs::WmGetRequest_<std::allocator<void> > WmGetRequest;

typedef boost::shared_ptr< ::skiros2_msgs::WmGetRequest > WmGetRequestPtr;
typedef boost::shared_ptr< ::skiros2_msgs::WmGetRequest const> WmGetRequestConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmGetRequest_<ContainerAllocator>::GET =
        
          "get"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmGetRequest_<ContainerAllocator>::GET_TEMPLATE =
        
          "get_template"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmGetRequest_<ContainerAllocator>::RESOLVE =
        
          "resolve"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmGetRequest_<ContainerAllocator>::GET_RECURSIVE =
        
          "get_recursive"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::WmGetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::WmGetRequest_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmGetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.context == rhs.context &&
    lhs.element == rhs.element &&
    lhs.relation_filter == rhs.relation_filter &&
    lhs.type_filter == rhs.type_filter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::WmGetRequest_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmGetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c9b805060dd287fc93adef8c3d20d63";
  }

  static const char* value(const ::skiros2_msgs::WmGetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c9b805060dd287fULL;
  static const uint64_t static_value2 = 0xc93adef8c3d20d63ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/WmGetRequest";
  }

  static const char* value(const ::skiros2_msgs::WmGetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Possible actions\n"
"string GET=get\n"
"string GET_TEMPLATE=get_template\n"
"string RESOLVE=resolve\n"
"string GET_RECURSIVE=get_recursive\n"
"\n"
"string action\n"
"string context\n"
"WmElement element\n"
"string relation_filter\n"
"string type_filter\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/WmElement\n"
"string id\n"
"string type\n"
"string label\n"
"Property[] properties\n"
"Relation[] relations\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Property\n"
"string key\n"
"string dataValue\n"
"string dataType\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Relation\n"
"string subjectId\n"
"string predicate\n"
"string objectId\n"
;
  }

  static const char* value(const ::skiros2_msgs::WmGetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.context);
      stream.next(m.element);
      stream.next(m.relation_filter);
      stream.next(m.type_filter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WmGetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::WmGetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::WmGetRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action);
    s << indent << "context: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.context);
    s << indent << "element: ";
    s << std::endl;
    Printer< ::skiros2_msgs::WmElement_<ContainerAllocator> >::stream(s, indent + "  ", v.element);
    s << indent << "relation_filter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.relation_filter);
    s << indent << "type_filter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type_filter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WMGETREQUEST_H
