// Generated by gencpp from file skiros2_msgs/WmMonitor.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WMMONITOR_H
#define SKIROS2_MSGS_MESSAGE_WMMONITOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skiros2_msgs/WmElement.h>
#include <skiros2_msgs/Relation.h>

namespace skiros2_msgs
{
template <class ContainerAllocator>
struct WmMonitor_
{
  typedef WmMonitor_<ContainerAllocator> Type;

  WmMonitor_()
    : prev_snapshot_id()
    , snapshot_id()
    , stamp()
    , author()
    , action()
    , elements()
    , relation()  {
    }
  WmMonitor_(const ContainerAllocator& _alloc)
    : prev_snapshot_id(_alloc)
    , snapshot_id(_alloc)
    , stamp()
    , author(_alloc)
    , action(_alloc)
    , elements(_alloc)
    , relation(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _prev_snapshot_id_type;
  _prev_snapshot_id_type prev_snapshot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _snapshot_id_type;
  _snapshot_id_type snapshot_id;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _author_type;
  _author_type author;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_type;
  _action_type action;

   typedef std::vector< ::skiros2_msgs::WmElement_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::skiros2_msgs::WmElement_<ContainerAllocator> >> _elements_type;
  _elements_type elements;

   typedef std::vector< ::skiros2_msgs::Relation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::skiros2_msgs::Relation_<ContainerAllocator> >> _relation_type;
  _relation_type relation;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ADD)
  #undef ADD
#endif
#if defined(_WIN32) && defined(UPDATE)
  #undef UPDATE
#endif
#if defined(_WIN32) && defined(REMOVE)
  #undef REMOVE
#endif
#if defined(_WIN32) && defined(RESET)
  #undef RESET
#endif


  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> ADD;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> UPDATE;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> REMOVE;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> RESET;

  typedef boost::shared_ptr< ::skiros2_msgs::WmMonitor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::WmMonitor_<ContainerAllocator> const> ConstPtr;

}; // struct WmMonitor_

typedef ::skiros2_msgs::WmMonitor_<std::allocator<void> > WmMonitor;

typedef boost::shared_ptr< ::skiros2_msgs::WmMonitor > WmMonitorPtr;
typedef boost::shared_ptr< ::skiros2_msgs::WmMonitor const> WmMonitorConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmMonitor_<ContainerAllocator>::ADD =
        
          "add"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmMonitor_<ContainerAllocator>::UPDATE =
        
          "update"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmMonitor_<ContainerAllocator>::REMOVE =
        
          "remove"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      WmMonitor_<ContainerAllocator>::RESET =
        
          "reset"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::WmMonitor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::WmMonitor_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmMonitor_<ContainerAllocator2> & rhs)
{
  return lhs.prev_snapshot_id == rhs.prev_snapshot_id &&
    lhs.snapshot_id == rhs.snapshot_id &&
    lhs.stamp == rhs.stamp &&
    lhs.author == rhs.author &&
    lhs.action == rhs.action &&
    lhs.elements == rhs.elements &&
    lhs.relation == rhs.relation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::WmMonitor_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmMonitor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmMonitor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmMonitor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmMonitor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecc40ec88cb57baaf7cf8c07fd40a3c7";
  }

  static const char* value(const ::skiros2_msgs::WmMonitor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecc40ec88cb57baaULL;
  static const uint64_t static_value2 = 0xf7cf8c07fd40a3c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/WmMonitor";
  }

  static const char* value(const ::skiros2_msgs::WmMonitor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Possible actions\n"
"string ADD=add\n"
"string UPDATE=update\n"
"string REMOVE=remove\n"
"string RESET=reset\n"
"\n"
"#Metadata\n"
"string prev_snapshot_id\n"
"string snapshot_id\n"
"time stamp\n"
"#Change\n"
"string author\n"
"string action\n"
"WmElement[] elements\n"
"Relation[] relation\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/WmElement\n"
"string id\n"
"string type\n"
"string label\n"
"Property[] properties\n"
"Relation[] relations\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Property\n"
"string key\n"
"string dataValue\n"
"string dataType\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Relation\n"
"string subjectId\n"
"string predicate\n"
"string objectId\n"
;
  }

  static const char* value(const ::skiros2_msgs::WmMonitor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prev_snapshot_id);
      stream.next(m.snapshot_id);
      stream.next(m.stamp);
      stream.next(m.author);
      stream.next(m.action);
      stream.next(m.elements);
      stream.next(m.relation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WmMonitor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::WmMonitor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::WmMonitor_<ContainerAllocator>& v)
  {
    s << indent << "prev_snapshot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.prev_snapshot_id);
    s << indent << "snapshot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.snapshot_id);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "author: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.author);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action);
    s << indent << "elements[]" << std::endl;
    for (size_t i = 0; i < v.elements.size(); ++i)
    {
      s << indent << "  elements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skiros2_msgs::WmElement_<ContainerAllocator> >::stream(s, indent + "    ", v.elements[i]);
    }
    s << indent << "relation[]" << std::endl;
    for (size_t i = 0; i < v.relation.size(); ++i)
    {
      s << indent << "  relation[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skiros2_msgs::Relation_<ContainerAllocator> >::stream(s, indent + "    ", v.relation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WMMONITOR_H
