// Generated by gencpp from file skiros2_msgs/WmModifyResponse.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WMMODIFYRESPONSE_H
#define SKIROS2_MSGS_MESSAGE_WMMODIFYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skiros2_msgs/WmElement.h>

namespace skiros2_msgs
{
template <class ContainerAllocator>
struct WmModifyResponse_
{
  typedef WmModifyResponse_<ContainerAllocator> Type;

  WmModifyResponse_()
    : elements()  {
    }
  WmModifyResponse_(const ContainerAllocator& _alloc)
    : elements(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::skiros2_msgs::WmElement_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::skiros2_msgs::WmElement_<ContainerAllocator> >> _elements_type;
  _elements_type elements;





  typedef boost::shared_ptr< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WmModifyResponse_

typedef ::skiros2_msgs::WmModifyResponse_<std::allocator<void> > WmModifyResponse;

typedef boost::shared_ptr< ::skiros2_msgs::WmModifyResponse > WmModifyResponsePtr;
typedef boost::shared_ptr< ::skiros2_msgs::WmModifyResponse const> WmModifyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.elements == rhs.elements;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9ea1fc652bb3fd8cd1a82d7eaa8b40a";
  }

  static const char* value(const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9ea1fc652bb3fd8ULL;
  static const uint64_t static_value2 = 0xcd1a82d7eaa8b40aULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/WmModifyResponse";
  }

  static const char* value(const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#ADD/UPDATE/UPDATE_PROPERTIES: return updated elements REMOVE/REMOVE_RECURSIVE: return nothing\n"
"WmElement[] elements\n"
"\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/WmElement\n"
"string id\n"
"string type\n"
"string label\n"
"Property[] properties\n"
"Relation[] relations\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Property\n"
"string key\n"
"string dataValue\n"
"string dataType\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Relation\n"
"string subjectId\n"
"string predicate\n"
"string objectId\n"
;
  }

  static const char* value(const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WmModifyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::WmModifyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::WmModifyResponse_<ContainerAllocator>& v)
  {
    s << indent << "elements[]" << std::endl;
    for (size_t i = 0; i < v.elements.size(); ++i)
    {
      s << indent << "  elements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skiros2_msgs::WmElement_<ContainerAllocator> >::stream(s, indent + "    ", v.elements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WMMODIFYRESPONSE_H
