// Generated by gencpp from file skiros2_msgs/WmQueryRelationsResponse.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WMQUERYRELATIONSRESPONSE_H
#define SKIROS2_MSGS_MESSAGE_WMQUERYRELATIONSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skiros2_msgs/Relation.h>

namespace skiros2_msgs
{
template <class ContainerAllocator>
struct WmQueryRelationsResponse_
{
  typedef WmQueryRelationsResponse_<ContainerAllocator> Type;

  WmQueryRelationsResponse_()
    : matches()  {
    }
  WmQueryRelationsResponse_(const ContainerAllocator& _alloc)
    : matches(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::skiros2_msgs::Relation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::skiros2_msgs::Relation_<ContainerAllocator> >> _matches_type;
  _matches_type matches;





  typedef boost::shared_ptr< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WmQueryRelationsResponse_

typedef ::skiros2_msgs::WmQueryRelationsResponse_<std::allocator<void> > WmQueryRelationsResponse;

typedef boost::shared_ptr< ::skiros2_msgs::WmQueryRelationsResponse > WmQueryRelationsResponsePtr;
typedef boost::shared_ptr< ::skiros2_msgs::WmQueryRelationsResponse const> WmQueryRelationsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.matches == rhs.matches;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator1> & lhs, const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skiros2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e325e0b48cc510fd9bcd6b7e064ef48";
  }

  static const char* value(const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e325e0b48cc510fULL;
  static const uint64_t static_value2 = 0xd9bcd6b7e064ef48ULL;
};

template<class ContainerAllocator>
struct DataType< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skiros2_msgs/WmQueryRelationsResponse";
  }

  static const char* value(const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Relation[] matches\n"
"\n"
"\n"
"================================================================================\n"
"MSG: skiros2_msgs/Relation\n"
"string subjectId\n"
"string predicate\n"
"string objectId\n"
;
  }

  static const char* value(const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.matches);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WmQueryRelationsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skiros2_msgs::WmQueryRelationsResponse_<ContainerAllocator>& v)
  {
    s << indent << "matches[]" << std::endl;
    for (size_t i = 0; i < v.matches.size(); ++i)
    {
      s << indent << "  matches[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skiros2_msgs::Relation_<ContainerAllocator> >::stream(s, indent + "    ", v.matches[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WMQUERYRELATIONSRESPONSE_H
