// Generated by gencpp from file skiros2_msgs/WmQueryRelations.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WMQUERYRELATIONS_H
#define SKIROS2_MSGS_MESSAGE_WMQUERYRELATIONS_H

#include <ros/service_traits.h>


#include <skiros2_msgs/WmQueryRelationsRequest.h>
#include <skiros2_msgs/WmQueryRelationsResponse.h>


namespace skiros2_msgs
{

struct WmQueryRelations
{

typedef WmQueryRelationsRequest Request;
typedef WmQueryRelationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WmQueryRelations
} // namespace skiros2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skiros2_msgs::WmQueryRelations > {
  static const char* value()
  {
    return "5c95783a21284fc96a095a71049fa510";
  }

  static const char* value(const ::skiros2_msgs::WmQueryRelations&) { return value(); }
};

template<>
struct DataType< ::skiros2_msgs::WmQueryRelations > {
  static const char* value()
  {
    return "skiros2_msgs/WmQueryRelations";
  }

  static const char* value(const ::skiros2_msgs::WmQueryRelations&) { return value(); }
};


// service_traits::MD5Sum< ::skiros2_msgs::WmQueryRelationsRequest> should match
// service_traits::MD5Sum< ::skiros2_msgs::WmQueryRelations >
template<>
struct MD5Sum< ::skiros2_msgs::WmQueryRelationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WmQueryRelations >::value();
  }
  static const char* value(const ::skiros2_msgs::WmQueryRelationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WmQueryRelationsRequest> should match
// service_traits::DataType< ::skiros2_msgs::WmQueryRelations >
template<>
struct DataType< ::skiros2_msgs::WmQueryRelationsRequest>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WmQueryRelations >::value();
  }
  static const char* value(const ::skiros2_msgs::WmQueryRelationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skiros2_msgs::WmQueryRelationsResponse> should match
// service_traits::MD5Sum< ::skiros2_msgs::WmQueryRelations >
template<>
struct MD5Sum< ::skiros2_msgs::WmQueryRelationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WmQueryRelations >::value();
  }
  static const char* value(const ::skiros2_msgs::WmQueryRelationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WmQueryRelationsResponse> should match
// service_traits::DataType< ::skiros2_msgs::WmQueryRelations >
template<>
struct DataType< ::skiros2_msgs::WmQueryRelationsResponse>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WmQueryRelations >::value();
  }
  static const char* value(const ::skiros2_msgs::WmQueryRelationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WMQUERYRELATIONS_H
