// Generated by gencpp from file skiros2_msgs/WoModify.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WOMODIFY_H
#define SKIROS2_MSGS_MESSAGE_WOMODIFY_H

#include <ros/service_traits.h>


#include <skiros2_msgs/WoModifyRequest.h>
#include <skiros2_msgs/WoModifyResponse.h>


namespace skiros2_msgs
{

struct WoModify
{

typedef WoModifyRequest Request;
typedef WoModifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WoModify
} // namespace skiros2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skiros2_msgs::WoModify > {
  static const char* value()
  {
    return "dd76bb6e56a5980cc554cb4a6047bd97";
  }

  static const char* value(const ::skiros2_msgs::WoModify&) { return value(); }
};

template<>
struct DataType< ::skiros2_msgs::WoModify > {
  static const char* value()
  {
    return "skiros2_msgs/WoModify";
  }

  static const char* value(const ::skiros2_msgs::WoModify&) { return value(); }
};


// service_traits::MD5Sum< ::skiros2_msgs::WoModifyRequest> should match
// service_traits::MD5Sum< ::skiros2_msgs::WoModify >
template<>
struct MD5Sum< ::skiros2_msgs::WoModifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WoModify >::value();
  }
  static const char* value(const ::skiros2_msgs::WoModifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WoModifyRequest> should match
// service_traits::DataType< ::skiros2_msgs::WoModify >
template<>
struct DataType< ::skiros2_msgs::WoModifyRequest>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WoModify >::value();
  }
  static const char* value(const ::skiros2_msgs::WoModifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skiros2_msgs::WoModifyResponse> should match
// service_traits::MD5Sum< ::skiros2_msgs::WoModify >
template<>
struct MD5Sum< ::skiros2_msgs::WoModifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WoModify >::value();
  }
  static const char* value(const ::skiros2_msgs::WoModifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WoModifyResponse> should match
// service_traits::DataType< ::skiros2_msgs::WoModify >
template<>
struct DataType< ::skiros2_msgs::WoModifyResponse>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WoModify >::value();
  }
  static const char* value(const ::skiros2_msgs::WoModifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WOMODIFY_H
