// Generated by gencpp from file skiros2_msgs/WoQuery.msg
// DO NOT EDIT!


#ifndef SKIROS2_MSGS_MESSAGE_WOQUERY_H
#define SKIROS2_MSGS_MESSAGE_WOQUERY_H

#include <ros/service_traits.h>


#include <skiros2_msgs/WoQueryRequest.h>
#include <skiros2_msgs/WoQueryResponse.h>


namespace skiros2_msgs
{

struct WoQuery
{

typedef WoQueryRequest Request;
typedef WoQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WoQuery
} // namespace skiros2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skiros2_msgs::WoQuery > {
  static const char* value()
  {
    return "c279e11806ad32f0e36af84c5a02aba8";
  }

  static const char* value(const ::skiros2_msgs::WoQuery&) { return value(); }
};

template<>
struct DataType< ::skiros2_msgs::WoQuery > {
  static const char* value()
  {
    return "skiros2_msgs/WoQuery";
  }

  static const char* value(const ::skiros2_msgs::WoQuery&) { return value(); }
};


// service_traits::MD5Sum< ::skiros2_msgs::WoQueryRequest> should match
// service_traits::MD5Sum< ::skiros2_msgs::WoQuery >
template<>
struct MD5Sum< ::skiros2_msgs::WoQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WoQuery >::value();
  }
  static const char* value(const ::skiros2_msgs::WoQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WoQueryRequest> should match
// service_traits::DataType< ::skiros2_msgs::WoQuery >
template<>
struct DataType< ::skiros2_msgs::WoQueryRequest>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WoQuery >::value();
  }
  static const char* value(const ::skiros2_msgs::WoQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skiros2_msgs::WoQueryResponse> should match
// service_traits::MD5Sum< ::skiros2_msgs::WoQuery >
template<>
struct MD5Sum< ::skiros2_msgs::WoQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skiros2_msgs::WoQuery >::value();
  }
  static const char* value(const ::skiros2_msgs::WoQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skiros2_msgs::WoQueryResponse> should match
// service_traits::DataType< ::skiros2_msgs::WoQuery >
template<>
struct DataType< ::skiros2_msgs::WoQueryResponse>
{
  static const char* value()
  {
    return DataType< ::skiros2_msgs::WoQuery >::value();
  }
  static const char* value(const ::skiros2_msgs::WoQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKIROS2_MSGS_MESSAGE_WOQUERY_H
