# ROS CONTROLLER SETTINGS
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur_arm_shoulder_pan_joint
    - ur_arm_shoulder_lift_joint
    - ur_arm_elbow_joint
    - ur_arm_wrist_1_joint
    - ur_arm_wrist_2_joint
    - ur_arm_wrist_3_joint

  stop_trajectory_duration: 0.1
  state_publish_rate:  25
  action_monitor_rate: 10

# gripper_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - gripper_finger1_joint
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10


  
