# Simulation settings for using moveit_sim_controllers
# moveit_sim_hw_interface:
#   joint_model_group: gripper
#   joint_model_group_pose: close
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ur_arm_shoulder_pan_joint
    - ur_arm_shoulder_lift_joint
    - ur_arm_elbow_joint
    - ur_arm_wrist_1_joint
    - ur_arm_wrist_2_joint
    - ur_arm_wrist_3_joint
    # - gripper_finger1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur_arm_shoulder_pan_joint
      - ur_arm_shoulder_lift_joint
      - ur_arm_elbow_joint
      - ur_arm_wrist_1_joint
      - ur_arm_wrist_2_joint
      - ur_arm_wrist_3_joint
# gripper_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     gripper_finger1_joint
#   gains:
#     gripper_finger1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - ur_arm_shoulder_pan_joint
    - ur_arm_shoulder_lift_joint
    - ur_arm_elbow_joint
    - ur_arm_wrist_1_joint
    - ur_arm_wrist_2_joint
    - ur_arm_wrist_3_joint
  gains:
    ur_arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur_arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur_arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur_arm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur_arm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur_arm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1