// Auto-generated. Do not edit!

// (in-package skiros2_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AssignTaskResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.progress_code = null;
      this.progress_message = null;
    }
    else {
      if (initObj.hasOwnProperty('progress_code')) {
        this.progress_code = initObj.progress_code
      }
      else {
        this.progress_code = 0;
      }
      if (initObj.hasOwnProperty('progress_message')) {
        this.progress_message = initObj.progress_message
      }
      else {
        this.progress_message = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AssignTaskResult
    // Serialize message field [progress_code]
    bufferOffset = _serializer.int16(obj.progress_code, buffer, bufferOffset);
    // Serialize message field [progress_message]
    bufferOffset = _serializer.string(obj.progress_message, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AssignTaskResult
    let len;
    let data = new AssignTaskResult(null);
    // Deserialize message field [progress_code]
    data.progress_code = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [progress_message]
    data.progress_message = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.progress_message.length;
    return length + 6;
  }

  static datatype() {
    // Returns string type for a message object
    return 'skiros2_msgs/AssignTaskResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '618c38785819b45ec2970116048e0af3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int16 progress_code
    string progress_message
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AssignTaskResult(null);
    if (msg.progress_code !== undefined) {
      resolved.progress_code = msg.progress_code;
    }
    else {
      resolved.progress_code = 0
    }

    if (msg.progress_message !== undefined) {
      resolved.progress_message = msg.progress_message;
    }
    else {
      resolved.progress_message = ''
    }

    return resolved;
    }
};

module.exports = AssignTaskResult;
