/amcl/base_frame_id:                                  'base_footprint'
/move_base/local_costmap/inflation/inflation_radius:  0.075
/move_base/DWAPlannerROS/xy_goal_tolerance:           0.2
/amcl/laser_max_beams:                                120
/amcl/min_particles:                                  1000
# /amcl/odom_frame_id:                                  'odom_hector'
/amcl/laser_min_range:                                -1.0
/amcl/laser_max_range:                                12.0
/amcl/laser_max_beams:                                120
/amcl/laser_model_type:                               'likelihood_field'
/amcl/laser_sigma_hit:                                0.2
/amcl/laser_z_hit:                                    0.5
/amcl/laser_z_max:                                    0.05
/amcl/laser_z_rand:                                   0.5
/amcl/laser_z_short:                                  0.05
/amcl/max_particles:                                  2000
/amcl/min_particles:                                  1000
/amcl/resample_interval:                              1
/amcl/save_pose_rate:                                 0.5
/amcl/transform_tolerance:                            1.0
/amcl/update_min_a:                                   0.2
/amcl/update_min_d:                                   0.25
/amcl/use_map_topic:                                  true
/amcl/kld_err:                                        0.05
/amcl/kld_z:                                          0.99