scan_filter_chain:
# - name: range
#   type: laser_filters/LaserScanRangeFilter
#   params:
#     use_message_range_limits: false
#     lower_threshold: 1.0
#     upper_threshold: .inf
#     lower_replacement_value: -.inf
#     upper_replacement_value: .inf
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -0.256312915875
    upper_angle: 0.256312915875